[package]
name = "miru-i18n-helper"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
hex = "0.4.3"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
ring = "0.17.8"
serde_json = "1.0.133"
